---
- hosts: localhost
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

  roles:
    - role: macos
      tags: ['macos']
    - role: homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      tags: ['mas']
    - role: zsh
      tags: ['zsh']
    - role: geerlingguy.dotfiles
      tags: ['dotfiles']
