---
- name: Tap versent/homebrew-taps
  homebrew_tap:
    name: versent/homebrew-taps

- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Install/upgrade Homebrew packages
  homebrew:
    name: '{{ homebrew_installed_packages }}'
    state: latest
  when: homebrew_installed_packages

- name: Install/upgrade Homebrew casks
  homebrew_cask:
    name: '{{ homebrew_installed_casks }}'
    state: upgraded
  when: homebrew_installed_casks
